# Generated by Django 2.0.2 on 2018-02-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='client_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
